---
title: "Initial R Markdown document"
author: "Sean M. Smith"
output: html_document
date: "2024-05-29"
editor_options: 
  markdown: 
    wrap: 72
---

**bold** *italics*

A list: 

1. one thing 
2. another thing 
1. a third


``` {r load-library}
library(gapminder)
head(gapminder)
```


```{r load-libs, echo=FALSE, message=FALSE}
library(ggplot2)

```

```{r make-plot}
plot(lifeExp ~ year, data=gapminder)
```

### The population of Afghanistan in 1952 was `r gapminder$pop[1]`

```{r}
ggplot(data = gapminder, mapping = aes(x = year, y = lifeExp, group = country)) +
  geom_point() + geom_line(mapping = aes(color = continent))
```
```{r}
ggplot(data = gapminder, mapping = aes(x = gdpPercap, y = lifeExp)) +
  geom_point(size = 2, alpha = 0.5, mapping = aes(color=continent)) + 
  scale_x_log10() +geom_smooth(method="lm", size = 1)
```

```{r}
americas <- gapminder[gapminder$continent == "Asia", ]
lifeExp_plot <- ggplot(data = americas, mapping = aes(x = year, y = lifeExp, color = continent)) +
  geom_line() + 
  facet_wrap( ~ country) +
  labs(
    x = "Year",
    y = "Life Expectancy",
    title = "Figure 1",
    color = "Continent"
  ) +
  theme(axis.text.x = element_text(angle = 45))
lifeExp_plot
```

